#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=02:00:00
#PBS -N resampling

# PBS is a computer software that performs job-scheduling
# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana U
#
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli


set -e
set -x

# Make output directorie
mkdir -p out_dir_resampling

# Run the actual python code
singularity exec docker://brainlife/mne:0.23dev python3 resampling.py

# Delete the bids folder if it exists
if [ -d bids ]
then
    rm -r bids
fi
